#!/usr/bin/env bash
set -euo pipefail

WAL_COLORS="${WAL_COLORS:-${HOME}/.cache/wal/colors}"
OUTPUT="${DWM_XRESOURCES_OUT:-${HOME}/.cache/wal/dwm.Xresources}"

if [[ ! -r "$WAL_COLORS" ]]; then
    printf 'Fehler: pywal-Farbdatei nicht lesbar: %s\n' "$WAL_COLORS" >&2
    exit 1
fi

mapfile -t wal_palette < "$WAL_COLORS"

if (( ${#wal_palette[@]} < 16 )); then
    printf 'Fehler: Ungültige pywal-Palette in %s (mindestens 16 Farben erwartet).\n' \
        "$WAL_COLORS" >&2
    exit 1
fi

for i in "${!wal_palette[@]}"; do
    wal_palette[$i]="${wal_palette[$i]//$'\r'/}"
done

background="${wal_palette[0]}"
foreground="${wal_palette[7]}"

color0="${wal_palette[0]}"
color1="${wal_palette[1]}"
color2="${wal_palette[2]}"
color3="${wal_palette[3]}"
color4="${wal_palette[4]}"
color5="${wal_palette[5]}"
color6="${wal_palette[6]}"
color7="${wal_palette[7]}"
color8="${wal_palette[8]}"

require_color() {
    local name="$1"
    local value="${!name:-}"

    if [[ ! "$value" =~ ^#[0-9A-Fa-f]{6}$ ]]; then
        printf 'Fehler: Ungueltige oder fehlende Farbe %s: %s\n' "$name" "${value:-<leer>}" >&2
        exit 1
    fi
}

for value in background foreground color0 color1 color2 color3 color4 color5 color6 color7 color8; do
    require_color "$value"
done

hex_to_rgb() {
    local hex="${1#\#}"
    printf '%d %d %d\n' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

relative_luminance() {
    local r g b
    read -r r g b < <(hex_to_rgb "$1")

    awk -v r="$r" -v g="$g" -v b="$b" 'BEGIN {
        r /= 255; g /= 255; b /= 255;
        r = (r <= 0.04045) ? r / 12.92 : ((r + 0.055) / 1.055) ^ 2.4;
        g = (g <= 0.04045) ? g / 12.92 : ((g + 0.055) / 1.055) ^ 2.4;
        b = (b <= 0.04045) ? b / 12.92 : ((b + 0.055) / 1.055) ^ 2.4;
        printf "%.8f\n", 0.2126 * r + 0.7152 * g + 0.0722 * b;
    }'
}

contrast_ratio() {
    local l1 l2
    l1="$(relative_luminance "$1")"
    l2="$(relative_luminance "$2")"

    awk -v l1="$l1" -v l2="$l2" 'BEGIN {
        if (l1 < l2) { t = l1; l1 = l2; l2 = t }
        printf "%.3f\n", (l1 + 0.05) / (l2 + 0.05);
    }'
}

contrast_at_least() {
    local actual
    actual="$(contrast_ratio "$1" "$2")"
    awk -v actual="$actual" -v minimum="$3" 'BEGIN { exit !(actual >= minimum) }'
}

# A stable dark foundation prevents bright wallpapers from making dwm unusable.
# Pywal remains visible in the selected scheme and border whenever contrast permits.
normbgcolor="$background"
normfgcolor="$foreground"
normbordercolor="$color8"

if ! contrast_at_least "$normfgcolor" "$normbgcolor" 4.5; then
    normfgcolor="#e6edf3"
fi

if ! contrast_at_least "$normbordercolor" "$normbgcolor" 1.5; then
    normbordercolor="#4b5563"
fi

# Prefer pywal blue/cyan accents. Fall back to stable cyan when a palette does
# not distinguish selection sufficiently from the normal background.
selbgcolor="$color4"
if ! contrast_at_least "$selbgcolor" "$normbgcolor" 3.0; then
    selbgcolor="$color6"
fi
if ! contrast_at_least "$selbgcolor" "$normbgcolor" 3.0; then
    selbgcolor="#5e81ac"
fi

selbordercolor="$selbgcolor"

# Ensure readable text in selected tags/title areas. Use black or near-white,
# depending on which gives a better contrast against the selected background.
if contrast_at_least "#101418" "$selbgcolor" 4.5; then
    selfgcolor="#101418"
elif contrast_at_least "#f4f7fb" "$selbgcolor" 4.5; then
    selfgcolor="#f4f7fb"
else
    # The selected background is guaranteed to be distinguishable from normal
    # background, but can still be mid-tone. Favor a stable light foreground.
    selfgcolor="#f4f7fb"
fi

mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" <<EOF
! Automatically generated by generate-dwm-xresources.sh
! Source palette: ${WAL_COLORS}
! Do not edit: this file is replaced after every wallpaper change.
!
! These six names are used by the classic dwm xrdb patch.
dwm.normbgcolor:       ${normbgcolor}
dwm.normfgcolor:       ${normfgcolor}
dwm.normbordercolor:   ${normbordercolor}
dwm.selbgcolor:        ${selbgcolor}
dwm.selfgcolor:        ${selfgcolor}
dwm.selbordercolor:    ${selbordercolor}
!
! Optional semantic colors for status2d/custom extensions.
dwm.color0:             ${color0}
dwm.color1:             ${color1}
dwm.color2:             ${color2}
dwm.color3:             ${color3}
dwm.color4:             ${color4}
dwm.color5:             ${color5}
dwm.color6:             ${color6}
dwm.color7:             ${color7}
dwm.color8:             ${color8}
EOF

printf 'DWM-Xresources erzeugt: %s\n' "$OUTPUT"
printf '  normal:   fg %s / bg %s / border %s\n' "$normfgcolor" "$normbgcolor" "$normbordercolor"
printf '  selected: fg %s / bg %s / border %s\n' "$selfgcolor" "$selbgcolor" "$selbordercolor"
